apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: challengekids_mockserver
  description: challengekids_mockserver
  annotations:
    github.com/project-slug: crlsquilumba/challengekids_mockserver
    github.com/branch-count: "4"
    github.com/has-gitflow: "true"
    github.com/default-branch: "main"
    github.com/pending-develop: "9 commits"
  links:
    - url: https://github.com/crlsquilumba/challengekids_mockserver/tree/main
      title: "✅ main — producción"
      icon: github
    - url: https://github.com/crlsquilumba/challengekids_mockserver/tree/develop
      title: "🔧 develop (9 commits pendientes)"
      icon: github
    - url: https://github.com/crlsquilumba/challengekids_mockserver/tree/Fix-plataformadocente
      title: "🌿 Fix-plataformadocente"
      icon: github
    - url: https://github.com/crlsquilumba/challengekids_mockserver/tree/feature/mi-nueva-funcionalidad
      title: "🌿 feature/mi-nueva-funcionalidad"
      icon: github
spec:
  type: library
  lifecycle: production
  owner: user:default/guest
